name: Deploy Streamlit App to EC2
on:
  workflow_run: 
    workflows: ["Check and merge"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Rag
            git pull origin master
            source ~/myvenv/bin/activate

            nohup ~/myvenv/bin/streamlit run Frontend/trial.py \
              --server.address 0.0.0.0 \
              --server.port 8501 \
              > streamlit.log 2>&1 < /dev/null &
                        
